### ISSUE TITLE
add documentation to readme

### ISSUE THREAD

**Issue by jakejh** [hugheylab/co-occurence_statistics#2]
Can you add examples of how to use each search parameter?

**Comment by JSchoenbachler** [comment]
README in API folder is updated with examples and documentation for setup. See the following commits:

https://github.com/hugheylab/co-occurence_statistics/commit/e4bfc53f15609a0866da4dd10761f4aa8fdd457d

https://github.com/hugheylab/co-occurence_statistics/commit/76614e4b3b0a8509ad10ab6a5f2901ee0d3826ea
